### ISSUE TITLE
Cannot unpack file

### ISSUE THREAD

**Issue by nara0216** [bylaws/libadrenotools#11]
Hello, I don't know if I'm doing it wrong or incorrect but when I install the module it sends an error saying "ERROR: Cannot unpack file". providing screenshots below
![Screenshot_2023-04-26-17-11-09-947_ru iiec pydroid3](https://user-images.githubusercontent.com/131862771/234528979-57eb0135-983f-425c-9911-0025d22f1aac.jpg)
I'm really wondering if there's something I did wrong and hopefully i get an answer right away because I really wanna use this library. Thank you so much in advance.

**Comment by bylaws** [comment]
Uh idk what you're even attempting to do, adrenotools isn't a python library
