### ISSUE TITLE
Help installing Adreno tools

### ISSUE THREAD

**Issue by azhon4** [bylaws/libadrenotools#18]
Hey, I'm just wondering how to install adreno tools and how to update them?
Do I have to do it on a PC or can I do it on android

**Comment by rzk0ack** [comment]
Hey, have you found your solutions? I'm new too to this and seems to can't found the answer everywhere else

**Comment by Foul-Tarnished** [comment]
it needs to be integrated into each application.
It's not like you can replace gpu driver for the whole smartphone
