### ISSUE TITLE
3 questions/requests for this project..

### ISSUE THREAD

**Issue by oscarbg** [bylaws/libadrenotools#2]
Hi,
this project is exciting(!) for finally allowing updating Qualcomm drivers on some devices..

thinking about this project I have this 3 questions/requests:

1)Can share if there is some flag/env variable to Adreno Vulkan driver to enable additional (perhaps experimental?) extensions as seems for example some Qualcomm driver 512.615 roms expose lot of new exts more on Adreno 650 than even on Adreno 730 using same 512.615 driver:
http://vulkan.gpuinfo.org/compare.php?compare=compare&id%5B14524%5D=on&id%5B14505%5D=on#extensions

2)Qualcomm Vulkan drivers DB with download links? 
I know how to extract Vulkan driver from OTAs and factory images but lazy to download large files (2-4GB) to just extract vulkan Adreno driver.. and seem every one must do the same lenghty way.. do you know of some easier way to acquire it? if not would be nice if somebody maintained a site/DB with these drivers (only Qualcomm Vulkan driver ".so" file) updated regularly..
I know it's not the scope of this work, but wanted to ask anyway..

3)Finally it would be great also an equivalent libmalitools project, reason is now with Pixel 6 devices having Mali GPUs, seems we are getting frequently updated Mali drivers, Google is shipping newer Mali drivers on Android 13 developer previews, for example for Pixel 6:
Android 12         : Mali r32p1
Android 13 dp1  : Mali r34p0
Android 13 dp2  : Mali r35p0
Mali r35 already have 9 new VK extensions (see http://vulkan.gpuinfo.org/compare.php?compare=compare&id%5B14514%5D=on&id%5B13271%5D=on#extensions ) and 
and conformanceVersion 1.2.7.2 is vs 1.2.6.0 on r32p1 so new bug fixes..
on website says newest is r36 (https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-drivers/valhall-kernel) and seems plausible DP3 to ship with these drivers..
It would be nice for example to use this updated Mali drivers on Samsung Sxx devices which use Mali GPUs on Europe at least..
All this is to motivate to try doing a libmalitools project.. 
can you at least answer if you expect to be much work or most work can be shared by libadrenotools (like hooking functionality) and should not be much work left to enable..

Thanks.

**Comment by bylaws** [comment]
> Hi, this project is exciting(!) for finally allowing updating Qualcomm drivers on some devices..
> 
> thinking about this project I have this 3 questions/requests:
> 
> 1)Can share if there is some flag/env variable to Adreno Vulkan driver to enable additional (perhaps experimental?) extensions as seems for example some Qualcomm driver 512.615 roms expose lot of new exts more on Adreno 650 than even on Adreno 730 using same 512.615 driver: http://vulkan.gpuinfo.org/compare.php?compare=compare&id%5B14524%5D=on&id%5B14505%5D=on#extensions

See here https://gist.github.com/bylaws/04130932e2634d1c6a2a9729e3940d60
This config file can be edited without root using the file redirect adrenotools option
> 
> 2)Qualcomm Vulkan drivers DB with download links? I know how to extract Vulkan driver from OTAs and factory images but lazy to download large files (2-4GB) to just extract vulkan Adreno driver.. and seem every one must do the same lenghty way.. do you know of some easier way to acquire it? if not would be nice if somebody maintained a site/DB with these drivers (only Qualcomm Vulkan driver ".so" file) updated regularly.. I know it's not the scope of this work, but wanted to ask anyway..
We're trying to work on a standardized format for drivers since it'll be helpful for skyline too but currently have other priorities, it's definitely something I want to do though
> 3)Finally it would be great also an equivalent libmalitools project, reason is now with Pixel 6 devices having Mali GPUs, seems we are getting frequently updated Mali drivers, Google is shipping newer Mali drivers on Android 13 developer previews, for example for Pixel 6: Android 12 : Mali r32p1 Android 13 dp1 : Mali r34p0 Android 13 dp2 : Mali r35p0 Mali r35 already have 9 new VK extensions (see http://vulkan.gpuinfo.org/compare.php?compare=compare&id%5B14514%5D=on&id%5B13271%5D=on#extensions ) and and conformanceVersion 1.2.7.2 is vs 1.2.6.0 on r32p1 so new bug fixes.. on website says newest is r36 (https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-drivers/valhall-kernel) and seems plausible DP3 to ship with these drivers.. It would be nice for example to use this updated Mali drivers on Samsung Sxx devices which use Mali GPUs on Europe at least.. All this is to motivate to try doing a libmalitools project.. can you at least answer if you expect to be much work or most work can be shared by libadrenotools (like hooking functionality) and should not be much work left to enable..
> 
Uh the name adrenotools is a bit of a lie really, it should with Mali already I just didn't consider it originally, maybe it's best I rename to something else
> Thanks.

**Comment by oscarbg** [comment]
Hi,
thanks for answering!
1) must investigate the config file on how to forcibly enable more extensions than default..
2) good to know, hope it get's done eventually..
3) nice news, than Mali drivers can be updated also with this project.. has been tested already? if not maybe some minor bugfixes needed before it works..

also don't know if documented but should be specified if restrictions on supported GPU families for drivers updates apply..
for example Adreno r615 driver only works on Adreno 6xx GPUs so nobody tries to run on Adreno 530 for example..

I keep open for updates on point 2 but keep free to close if wanted..

**Comment by Trass3r** [comment]
> Uh the name adrenotools is a bit of a lie really, it should work with Mali already I just didn't consider it originally, maybe it's best I rename to something else

Sounds too good to be true. There are no adreno specific parts?
