### ISSUE TITLE
Fails to compile with NDK27 when flexible page size support is enabled due to PAGE_SIZE becoming undefined

### ISSUE THREAD

**Issue by rtiangha** [bylaws/libadrenotools#21]
I was playing around with some of the new NDK 27 features in my custom build of Citra, but encountered some build errors when I turned the options on.

According to [here](https://github.com/android/ndk/wiki/Changelog-r27):

> Android 15 will allow OEMs to ship arm64-v8a devices with 16KiB page sizes. Devices that use this configuration will not be able to run existing apps that use native code. To be compatible with these devices, applications will need to rebuild all their native code to be 16KiB aligned, and rewrite any code which assumes a specific page size.

From the same page, to enable such support:

> Set to APP_SUPPORT_FLEXIBLE_PAGE_SIZES := true in your Application.mk or pass -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON to CMake (via android.defaultConfig.externalNativeBuild.cmake.arguments if you're using the Android Gradle Plugin) to build your code to be compatible with devices that use a 16KiB page size.

I tried the using the cmake option in my Citra build to test, but got errors such as these:

```
/home/runner/work/bravely-offline-citra/bravely-offline-citra/externals/libadrenotools/lib/linkernsbypass/android_linker_ns.cpp:125:74: error: use of undeclared identifier 'PAGE_SIZE'
    125 |     return reinterpret_cast<void *>(reinterpret_cast<uintptr_t>(ptr) & ~(PAGE_SIZE - 1));
```

According to [this page](https://developer.android.com/guide/practices/page-sizes), it's because with this support enabled, PAGE_SIZE is no longer defined. Instead, they suggest using [getpagesize()](https://cs.android.com/android/platform/superproject/main/+/main:bionic/libc/bionic/getpagesize.cpp;l=32) or [sysconf(_SC_PAGESIZE)](https://cs.android.com/android/platform/superproject/main/+/main:bionic/libc/bionic/sysconf.cpp;l=151) to dynamically determine the page size.

Here were all the references to PAGE_SIZE that I could find:
```
grep -r PAGE_SIZE externals/libadrenotools/
externals/libadrenotools/lib/linkernsbypass/android_linker_ns.cpp:    return reinterpret_cast<void *>(reinterpret_cast<uintptr_t>(ptr) & ~(PAGE_SIZE - 1));
externals/libadrenotools/lib/linkernsbypass/android_linker_ns.cpp:        mprotect(align_ptr(reinterpret_cast<void *>(&dlopen)), PAGE_SIZE, PROT_WRITE | PROT_READ | PROT_EXEC);
externals/libadrenotools/lib/linkernsbypass/android_linker_ns.cpp:    mprotect(align_ptr(reinterpret_cast<void *>(&loader_dlopen)), PAGE_SIZE, PROT_WRITE | PROT_READ | PROT_EXEC);
externals/libadrenotools/src/bcenabler.cpp:    return reinterpret_cast<void *>(reinterpret_cast<uintptr_t>(ptr) & ~(PAGE_SIZE - 1));
externals/libadrenotools/src/bcenabler.cpp:    void *ptr{mmap(patchPage, PAGE_SIZE,  PROT_READ | PROT_WRITE | PROT_EXEC, MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, 0, 0)};
externals/libadrenotools/src/bcenabler.cpp:    if (mprotect(align_ptr(vkGetPhysicalDeviceFormatPropertiesFn), PAGE_SIZE * 2, PROT_WRITE | PROT_READ | PROT_EXEC))
externals/libadrenotools/src/bcenabler.cpp:    if (mprotect(align_ptr(convFormatFn), PAGE_SIZE * 2, PROT_WRITE | PROT_READ | PROT_EXEC))
externals/libadrenotools/src/bcenabler.cpp:    if (PatchRawData_size > PAGE_SIZE)
```

Anyway, I think libadrenotools will need a bit of work to fully support Android 15 and the new hardware that may be coming down the pipe. Of course, this also affects liblinkernsbypass as well.

**Comment by bylaws** [comment]
Feel free to submit a patch using getpagesize

**Comment by rtiangha** [comment]
Done.

libadrenotools PR: https://github.com/bylaws/libadrenotools/pull/22
liblinkernsbypass PR: https://github.com/bylaws/liblinkernsbypass/pull/3

Of course, once the submodule is updated, it'll need to be updated here as well for full Android 15 support. Wasn't sure how to do that without having to wait for the liblinkernsbypass PR to be merged first.

**Comment by rtiangha** [comment]
Thanks! One more PR to update the submodule and then this guy can be closed. https://github.com/bylaws/libadrenotools/pull/23
