### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by Jullegaming04** [bylaws/libadrenotools#3]
Where can i download this to my android with adreno 610?

**Comment by Jullegaming04** [comment]
Btw i have a rooted android with magisk. So is there any modules or apk i can download?

**Comment by leo60228** [comment]
This is a library to be used by app developers. It can not be used on its own. See https://docs.mesa3d.org/android.html for general Mesa on Android instructions, though you probably shouldn't be trying to replace your drivers as an end user.
