### ISSUE TITLE
Unable to build due to missing hook_impl

### ISSUE THREAD

**Issue by GPUCode** [bylaws/libadrenotools#9]
Hi and first all many thanks for this amazing library! I'm trying to integrate it into my project but have been facing issues getting it to build. More specifically I'm facing this error:

![εικόνα](https://user-images.githubusercontent.com/47210458/213712800-e480e048-4056-4306-a2a3-a29f32fb9088.png)

Opening the particular folder during the build, noticed the library was being built but immediately deleted for some reason. I'll also link to the integration commit in case there was a mistake on my part https://github.com/GPUCode/citra/commit/aed0baf1c71781b0ed11bca15a77dd92696a9aa9

**Comment by bylaws** [comment]
Double check you're on the latest cmake version offered by as, I've had issues reported with older ones
